Added makefile
paralus/cli pull request #23
Opened 2022-06-30 13:27 UTC by foss-pravin

### What does this PR change?

- Added initial makefile to compile pctl binary

### Does the PR depend on any other PRs or Issues? If yes, please list them.

-

### Checklist

I confirm, that I have...

- [ ] Read and followed the contributing guide in `CONTRIBUTING.md`
- [ ] Added tests for this PR
- [ ] Formatted the code using `go fmt` (if applicable)
- [ ] Updated [documentation on the Paralus docs site](https://github.com/paralus/website/blob/main/docs) (if applicable)
- [ ] Updated `CHANGELOG.md`

2022-07-01 08:00 UTC, meain requested changes
Hey @foss-pravin , thanks for working on this. Had a few nitpicks.

2022-07-05 12:16 UTC, niravparikh05 requested changes

2022-07-25 05:16 UTC, niravparikh05 commented
@foss-pravin few comments for you to address and then we should be good to go.

2023-02-01 17:53 UTC, akshay196 commented
Moved to https://github.com/paralus/cli/pull/43

2023-02-01 17:53 UTC, closed without merging